/* Copyright (c) 2018 paddlepaddle Authors. All Rights Reserved.\n\nLicensed under the Apache License, Version 2.0 (the "License");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an "AS IS" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License. */\n\n#include "lite/backends/x86/math/search_fc.h"\n#include <algorithm>\n#include <vector>\n
#if defined(__clang__)
#pragma clang attribute push (__attribute__((target("avx,avx2,fma,f16c"))), apply_to=any(function))
#elif defined(__GNUC__)
#pragma GCC push_options
#pragma GCC target("avx,avx2,fma,f16c")
#endif
\n\nnamespace paddle {\nnamespace lite {\nnamespace x86 {\nnamespace math {\n\n/*\n * All tensors' dimension should be the same and the values of\n * each dimension must be the same, except the axis dimension.\n */\ntemplate <typename T>\nclass SearchFcFunctor<lite::TargetType::kX86, T> {\n public:\n  void operator()(const lite::X86Context& context,\n                  const lite::Tensor& bottom,\n                  const lite::Tensor& w,\n                  const lite::Tensor& b,\n                  lite::Tensor* top,\n                  int out_size) {\n    int batch = bottom.dims()[0];\n\n    int _out = w.dims()[0];  // 100\n    int _in = w.dims()[1];   // 228\n\n    lite::DDim dims(std::vector<int64_t>({bottom.dims()[0], out_size}));\n\n    const auto bottom_data = bottom.data<T>();\n    auto top_data = top->template mutable_data<T>(lite::TargetType::kX86);\n    const auto weights = w.data<T>();\n    auto blas = math::GetBlas<lite::TargetType::kX86, T>(context);\n    call_gemm<lite::X86Context, T>(blas,\n                                   CblasNoTrans,\n                                   CblasTrans,\n                                   batch,\n                                   _out,\n                                   _in,\n                                   1.0f,\n                                   bottom_data,\n                                   weights,\n                                   0.0f,\n                                   top_data);\n    if (true) {\n      const auto* bias_data = b.data<T>();\n      for (int i = 0; i < batch; ++i) {\n        // add bias here\n        sse_eltadd(top_data + i * _out, bias_data, top_data + i * _out, _out);\n      }\n    }\n  }\n\n  // private:\n};\n\n#define DEFINE_FUNCTOR(type) \\n  template class SearchFcFunctor<lite::TargetType::kX86, type>;\n\nFOR_ALL_TYPES(DEFINE_FUNCTOR);\n\n}  // namespace math\n}  // namespace x86\n}  // namespace lite\n}  // namespace paddle\n
#if defined(__clang__)
#pragma clang attribute pop
#elif defined(__GNUC__)
#pragma GCC pop_options
#endif
