/* Copyright (c) 2016 PaddlePaddle Authors. All Rights Reserved.\n\nLicensed under the Apache License, Version 2.0 (the "License");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an "AS IS" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License. */\n\n#include "lite/backends/x86/math/sequence2batch.h"\n
#if defined(__clang__)
#pragma clang attribute push (__attribute__((target("avx,avx2,fma,f16c"))), apply_to=any(function))
#elif defined(__GNUC__)
#pragma GCC push_options
#pragma GCC target("avx,avx2,fma,f16c")
#endif
\n\nnamespace paddle {\nnamespace lite {\nnamespace x86 {\nnamespace math {\n\ntemplate <typename T>\nclass CopyMatrixRowsFunctor<lite::TargetType::kX86, T> {\n public:\n  void operator()(const lite::Context<lite::TargetType::kX86>& context,\n                  const lite::Tensor& src,\n                  const std::vector<uint64_t>& index_lod,\n                  lite::Tensor* dst,\n                  bool is_src_index) {\n    const uint64_t* index = index_lod.data();\n    const auto& src_dims = src.dims();\n    const auto& dst_dims = dst->dims();\n    CHECK_EQ(src_dims.size(), 2UL) << "The src must be matrix with rank 2.";\n    CHECK_EQ(dst_dims.size(), 2UL) << "The dst must be matrix with rank 2.";\n    CHECK_EQ(src_dims[1], dst_dims[1])\n        << "The width of src and dst must be same.";\n    auto height = dst_dims[0];\n    auto width = dst_dims[1];\n    auto* src_data = src.data<T>();\n    auto* dst_data = dst->template mutable_data<T>();\n    const int sz = width * sizeof(T);\n    if (is_src_index) {\n      for (int i = 0; i < height; ++i) {\n        memcpy(dst_data + i * width, src_data + index[i] * width, sz);\n      }\n    } else {\n      for (int i = 0; i < height; ++i) {\n        memcpy(dst_data + index[i] * width, src_data + i * width, sz);\n      }\n    }\n  }\n};\n\ntemplate class CopyMatrixRowsFunctor<lite::TargetType::kX86, float>;\ntemplate class CopyMatrixRowsFunctor<lite::TargetType::kX86, double>;\n\ntemplate class LoDTensor2BatchFunctor<lite::TargetType::kX86, float>;\ntemplate class LoDTensor2BatchFunctor<lite::TargetType::kX86, double>;\ntemplate class Batch2LoDTensorFunctor<lite::TargetType::kX86, float>;\ntemplate class Batch2LoDTensorFunctor<lite::TargetType::kX86, double>;\n\n}  // namespace math\n}  // namespace x86\n}  // namespace lite\n}  // namespace paddle\n
#if defined(__clang__)
#pragma clang attribute pop
#elif defined(__GNUC__)
#pragma GCC pop_options
#endif
